### ISSUE TITLE
configure open graph variables

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/catalog-biodiversity-frontend#13]
http://ogp.me/

og:title = "Catálogo de Especies de la biodiversidad de Colombia"
og:type = website 
og:image = http://www.biodiversidad.co/images/logo_catalogo_especies.png
og:url = www.biodiversidad.co

**Comment by valegrajales** [comment]
Fixed in 18689eb94138af599be22a7f1d2d7ad701105a9f
