### ISSUE TITLE
Sección Datos Básicos

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/catalog-biodiversity-frontend#18]
Ocultar la sección para los usuarios (Actual Rol Editor). Esta sección solo sirve para aceptar la creación de una nueva ficha, los campos se llenan automáticamente. 

a. Al oprimir "+ Nueva Ficha" en el panel izquierdo se cree atomaticamente la ficha sin ningun paso adicional.
b. Que no sea necesario darle guardar en datos básicos para que la ficha se cree, datos básicos no seria visible para el ususario.

![image](https://cloud.githubusercontent.com/assets/5700527/3315030/de61ff88-f6f6-11e3-9224-ac73941a4f3f.png)

**Comment by andresciceri** [comment]
c7adea0bc09fa63a3f0e80845aab5b13130885e6

The editor user can create a new card in 1 step, where the previous information is create before to show the complete form. But the admin user has to do the previous step because he hasn't a default contact.
