### ISSUE TITLE
Secciones de la página de edición de la ficha

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/catalog-biodiversity-frontend#19]
1. Ocultar la sección "Citación" tanto para administradores como usuarios
2. Cambiar el orden de las secciones:

Datos Básicos (Tener en cuenta el issue #18 )
Info. Taxonómica
Nombres Comunes
Distribución Geográfica
Atributos
Contacto

El pantallazo muestra la visualización deseada

![image](https://cloud.githubusercontent.com/assets/5700527/3315135/e08c73a0-f6f7-11e3-9b94-c9cec04aaa37.png)

**Comment by andresciceri** [comment]
5e5b3c01e3b9bdd3ab701097d723c838ee09dcbf

The tab "Citacion" has been hidden and the tab order has been changed. The tab about Basic Data has been hidden only for editor users.
