### ISSUE TITLE
Seciciones del Panel Laterl Izq

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/catalog-biodiversity-frontend#20]
Cambiar títulos 
• Citaciones por Bibliografía
• Nueva cita por Nueva referencia

El pantallazo muestra la visualización deseada

![image](https://cloud.githubusercontent.com/assets/5700527/3315259/e36cf7b0-f6f8-11e3-80e6-589fc6127c99.png)

**Comment by andresciceri** [comment]
b10b039c45584a02247d8c8365836ba353722b3a

The menu on the left has been changed with the new text.
