### ISSUE TITLE
Sección Información Taxonómica

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/catalog-biodiversity-frontend#21]
• Ocultar los campos
Ficha nomenclatural en el archivo de autoridad taxonómica (hipervínculo)
• Dividir a nivel de interfaz el campo Jerarquía taxonómica en 7
Reino
Filo
Clase
Orden
Familia
Género
Epíteto específico
• Modificar elemento Página WEB por Enlace EOL

![image](https://cloud.githubusercontent.com/assets/5700527/3315297/47c389b8-f6f9-11e3-9790-18b89a02969f.png)

**Comment by andresciceri** [comment]
555599119406cf665531646f8e6767273b922846
The Taxonomic information has been changed with a new form.
