### ISSUE TITLE
Agregar un nombre común nuevo (no disponible en la lista)

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/catalog-biodiversity-frontend#22]
• Ocultar los elementos
Enlace al término en el tesauro
Tesauro completo

![image](https://cloud.githubusercontent.com/assets/5700527/3315349/a4dc6b24-f6f9-11e3-959f-c84b7ee7a9b4.png)

**Comment by andresciceri** [comment]
b10b039c45584a02247d8c8365836ba353722b3a

The inputs (Enlace al término en el tesauro, Tesauro completo) has been deleted.
