### ISSUE TITLE
Lista de nombres comunes disponibles

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/catalog-biodiversity-frontend#23]
• Ocultar las columnas
ID Tesauro
Tesauro completo

El pantallazo muestra la visualización deseada

![image](https://cloud.githubusercontent.com/assets/5700527/3315365/c784601e-f6f9-11e3-8dc4-beb26d21ccca.png)

**Comment by andresciceri** [comment]
f04a76b20ea72a82a045045310cf1800ac69d342

The colums (ID Tesauro,Tesauro completo) have been deleted.
