### ISSUE TITLE
Distribución Geográfica

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/catalog-biodiversity-frontend#24]
• Ocultar las secciones 
Corporaciones Autónomas Regionales
Organizaciones

El pantallazo muestra la visualización deseada

![image](https://cloud.githubusercontent.com/assets/5700527/3315516/eeee1090-f6fa-11e3-8c32-9a9ff6e47114.png)

**Comment by andresciceri** [comment]
293d17f1c573dd34ab39e936e7a4e491abc6ca29

The sections (Corporaciones Autónomas Regionales, Organizaciones) have been hidden.
