### ISSUE TITLE
Distribución Geográfica- IDs

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/catalog-biodiversity-frontend#25]
Ocultar los ID en las dos subsecciones Departamentos y Regiones Naturales

El pantallazo muestra la visualización deseada

![image](https://cloud.githubusercontent.com/assets/5700527/3315569/47683af2-f6fb-11e3-9717-6431424291d1.png)

**Comment by andresciceri** [comment]
74e3fb51175f5d7a63f465b85b21818b9715b75f

The id columns has been hidden.
