### ISSUE TITLE
Atributos 1

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/catalog-biodiversity-frontend#26]
Se requiere ocultar los siguientes Atributos

Asociado al Issue #27 

(-)indica la categoria bajo la cual se encuentran los atributos

-Etimología del nombre científico
Etimología del nombre científico

-Distribución
Distribución geográfica en el mundo
Región natural
Ecosistema

-Historia Natural
Origen

-Taxonomía
Información de tipos

-Más Información
Metadatos
Recursos multimedia

-Créditos
Revisor(es)
Colaborador(es)

-Multimedia
Imagen
Mapa
Video
Sonido

**Comment by andresciceri** [comment]
83b7a161ee8890e1da0f5ad6e7818828f51ad7f5

The attributes has been deleted.
