### ISSUE TITLE
Atributos 2

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/catalog-biodiversity-frontend#27]
A continuación se muestra el listado de los atributos que se desean mantener, incluye cambios de categoria y nombres.

Asociado al Issue #26 

(-)indica la categoria bajo la cual se encuentran los atributos

-Distribución
Distribución geográfica (Antes: distribución geográfica en Colombia)
Distribución altitudinal

-Historia Natural
Descripción (Antes: Descripción general)
Hábitat
Hábito
Alimentación
Comportamiento
Vocalizaciones
Reproducción
Ecología
Demografía (Antes: Estado actual de la población, bajo la categoría Estado de conservación)

-Invasión
¿Es invasora? 
Descripción de la invasión 
Impactos
Plan de manejo  (Antes: Mecanismos de control)

-Taxonomía
Descripción taxonómica
Claves taxonómicas
Sinónimos (Antes: bajo la categoría Más Información)

-Estado de conservación
Estado de amenaza según categorías UICN
En Colombia
En el mundo
Estado CITES
Amenazas (Antes: Factores de amenaza)
Manejo y Conservación (Antes: Medidas de conservación)

-Usos (Antes: Uso y tráfico)
Información de usos

-Bibliografía (Antes: Más Información)
Recursos en Internet
Referencias bibliográficas

-Partes asociadas (Antes: Créditos)
Proveedores de contenidos (Antes: Autor)
Editores
Créditos específicos

-Multimedia
Recursos multimedia (Antes: bajo la categoría Más Información)

**Comment by andresciceri** [comment]
83b7a161ee8890e1da0f5ad6e7818828f51ad7f5

The attributes has been changed and the table's title by default in the attribute's form has been corrected. The card's view has been changed too.

**Comment by nestorjal** [comment]
The overall "Atributo" drop-down list looks fine, but the attribute "Registros biólogicos" in "Descripción" section, remains available.
