### ISSUE TITLE
Vista general de los atributos

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/catalog-biodiversity-frontend#28]
El atributo Estado de amenaza según UICN aparece por defecto en la sección de atributos, ocultar/eliminar.

![image](https://cloud.githubusercontent.com/assets/5700527/3315920/97c3b36c-f6fd-11e3-9532-937afa1ad878.png)

**Comment by andresciceri** [comment]
83b7a161ee8890e1da0f5ad6e7818828f51ad7f5

The attributes has been changed and the table's title by default in the attribute's form has been corrected. The card's view has been changed too.
