### ISSUE TITLE
Vista de las fichas desde el catálogo

### ISSUE THREAD

**Issue by camiplata** [SIB-Colombia/catalog-biodiversity-frontend#29]
Ocultar los elementos:
• ID Citación
• ID Contacto
• Título del metadato (hipervínculo)
• Ficha nomenclatural en el archivo de autoridad taxonómica (hipervínculo)

![image](https://cloud.githubusercontent.com/assets/5700527/3315947/d80203de-f6fd-11e3-8339-12de0f476c58.png)

**Comment by andresciceri** [comment]
83b7a161ee8890e1da0f5ad6e7818828f51ad7f5

The attributes has been changed and the table's title by default in the attribute's form has been corrected. The card's view has been changed too.

**Comment by nestorjal** [comment]
The elements "ID Citación" and "ID Contacto" are still visible in the table.
