### ISSUE TITLE
Make sure that labels of empty fields are hidden

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/catalog-biodiversity-frontend#34]
Some fields has empty values, nonetheless the label of the field appears in the page

please make sure this fields are hidden

![captura de pantalla 2014-09-17 a la s 11 05 26](https://cloud.githubusercontent.com/assets/3705866/4306902/8270071c-3e84-11e4-85bd-278ab7cf2bf8.png)

**Comment by valegrajales** [comment]
Fixed in 82679b467085cb389722e285c17fa4aeb0ecc926
