### ISSUE TITLE
Change displaying of the sort control

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/catalog-biodiversity-frontend#35]
The current "sort control" position is not a clear function for the end user

![captura de pantalla 2014-09-17 a la s 11 07 17](https://cloud.githubusercontent.com/assets/3705866/4306958/03924580-3e85-11e4-8dbd-7dd7ba92c6d1.png)

Please change the way and position of it

An option could be as a floating menu over the fact-sheets preview list, like a fancy version of:
![image](https://cloud.githubusercontent.com/assets/3705866/4307101/73083f0e-3e86-11e4-8ac6-224c5255ed58.png)

**Comment by valegrajales** [comment]
Fixed in 15b5e88536de1a3b99740fdeac3ca27cacf682be
