### ISSUE TITLE
Include images from the EOL API

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/catalog-biodiversity-frontend#36]
Please include in the fact-sheets images from the EOL API
http://eol.org/api

Please use asynchronous data retrieving to avoid making slow the page rendering

**Comment by valegrajales** [comment]
Initial support in 8b86ab727c2af2958de37417788ad8b89a60ca0f

**Comment by valegrajales** [comment]
Fixed in 87c324cfd93857c791413af1379739dcb76517a5
