### ISSUE TITLE
Change dropdown list 

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/catalog-biodiversity-frontend#39]
Please rename the "grupo biológico" dropdown to "categorías"
and include "humedales" and "paramos" options

This options should not work as filter but as a link to the 'paramos' and 'humedales' sub-catalog

![captura de pantalla 2015-01-13 a la s 9 21 30](https://cloud.githubusercontent.com/assets/3705866/5722033/7c7cf660-9b06-11e4-9ee2-c42843836484.png)

**Comment by valegrajales** [comment]
Fixed in 5d2ae34cb77fe60d862c39beae2d9b159687cc70
