### ISSUE TITLE
Distribution map with data from data portal

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/catalog-biodiversity-frontend#41]
Please, use leaflet.js to include a distribution map per each specie

take the data from the "SIB Data Portal API v 0.2 GeoJSON"
https://github.com/SIB-Colombia/dataportal-explorer/wiki/SIB-Data-Portal-API-v-0.2-GeoJSON-query-to-biological-records

**Comment by mcubillos** [comment]
Distribution map created in f577fe052c78a1d8d18127f59d95ec5658977484
