### ISSUE TITLE
Carrousel still appearing when no image

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/catalog-biodiversity-frontend#44]
Carrousel arrows still appearing when no images available
http://www.biodiversidad.co/fichas/4151

In addition, the default-no-image image is not appearing

**Comment by danipilze** [comment]
is this done?

**Comment by valegrajales** [comment]
Yes, this issue was fixed when we started to use our https://github.com/SIB-Colombia/photo-gallery (photo-gallery library) 8c9e9789f8d0502e134c29d7604a8095158fa776
