### ISSUE TITLE
Hide "Ficha nomenclatural"

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/catalog-biodiversity-frontend#45]
please hide the link and the label of "Ficha Nomenclatural"
![nomenclatural](https://cloud.githubusercontent.com/assets/3705866/6308975/c3bb8b3a-b916-11e4-865e-8e8b6c097883.PNG)

**Comment by mcubillos** [comment]
Fixed in 4708cdc985e91cdf87c89e821e88175500b83517
